[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && npm start"
restartPolicyType = "on_failure"

[environments.production]
variables = { NODE_ENV = "production" }

[[services]]
source = "server" 